version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10

    working_directory: ~/overdive/nuxtsample

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run:
          name: 'Install Dependecies'
          command: yarn global add firebase-tools

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn generate
      - run:
          name: 'Deploy to Hosting'
          command: >- 
          ln -s ./node_modules/firebase-tools/bin/firebase . && 
          ./firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  standard-workflow:
    jobs:
      - deploy:
          requires:
              - build
          filters:
              branches:
                  only:
                      - master
